### ISSUE TITLE
AttributeError: 'QlRegisterManager' object has no attribute 'w9'

### ISSUE THREAD

**Issue by WYK15** [pcy190/deobfuscator#3]
I run main.py ，But it raises this：
```
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    emulator.search_path(strategy=0)  # or strategy=1
  File "/Users/wangyankun/Documents/deobfuscator-master/emulator.py", line 471, in search_path
    ql.run(begin=bb.start_addr)
  File "/Library/Python/3.7/site-packages/qiling/core.py", line 197, in run
    self.os.run()
  File "/Library/Python/3.7/site-packages/qiling/os/linux/linux.py", line 125, in run
    self.ql.emu_start(self.ql.loader.elf_entry, self.exit_point, self.ql.timeout, self.ql.count)
  File "/Library/Python/3.7/site-packages/qiling/core.py", line 259, in emu_start
    raise self.internal_exception
  File "/Library/Python/3.7/site-packages/qiling/utils.py", line 19, in wrapper
    return func(*args, **kw)
  File "/Library/Python/3.7/site-packages/qiling/core_hooks.py", line 159, in _hook_trace_cb
    ret = h.call(ql, addr, size)
  File "/Library/Python/3.7/site-packages/qiling/core_hooks.py", line 36, in call
    return self.callback(ql, *args)
  File "/Users/wangyankun/Documents/deobfuscator-master/emulator.py", line 158, in guide_hook
    reg2_val = ql.reg.__getattribute__(reg2)
  File "/Library/Python/3.7/site-packages/qiling/arch/register.py", line 28, in __getattribute__
    return super(QlRegisterManager, self).__getattribute__(name)
AttributeError: 'QlRegisterManager' object has no attribute 'w9'
```

**Comment by WYK15** [comment]
solved,I removed old version qiling and installed qiling 1.2 from here,https://github.com/qilingframework/qiling/releases/tag/1.2.

**Comment by simhigo** [comment]
I had the same problem, thank you for solving it
