### ISSUE TITLE
AttributeError: module 'keystone' has no attribute 'KS_ARCH_ARM64'

### ISSUE THREAD

**Issue by shabanam1982** [pcy190/deobfuscator#8]
(venv)─(kali㉿kali)-[~/deobfuscator]
└─$ python3 main.py
Traceback (most recent call last):
  File "/home/kali/deobfuscator/main.py", line 1, in <module>
    from analyzer import DeflatAnalyzer
  File "/home/kali/deobfuscator/analyzer.py", line 4, in <module>
    import angr.analyses.analysis
  File "/home/kali/path/to/venv/lib/python3.12/site-packages/angr/__init__.py", line 41, in <module>
    from .sim_procedure import SimProcedure
  File "/home/kali/path/to/venv/lib/python3.12/site-packages/angr/sim_procedure.py", line 9, in <module>
    from cle import SymbolType
  File "/home/kali/path/to/venv/lib/python3.12/site-packages/cle/__init__.py", line 13, in <module>
    from .backends import (
  File "/home/kali/path/to/venv/lib/python3.12/site-packages/cle/backends/__init__.py", line 3, in <module>
    from .backend import ALL_BACKENDS, Backend, ExceptionHandling, FunctionHint, FunctionHintSource, register_backend
  File "/home/kali/path/to/venv/lib/python3.12/site-packages/cle/backends/backend.py", line 9, in <module>
    import archinfo
  File "/home/kali/path/to/venv/lib/python3.12/site-packages/archinfo/__init__.py", line 20, in <module>
    from .arch_aarch64 import ArchAArch64
  File "/home/kali/path/to/venv/lib/python3.12/site-packages/archinfo/arch_aarch64.py", line 22, in <module>
    class ArchAArch64(Arch):
  File "/home/kali/path/to/venv/lib/python3.12/site-packages/archinfo/arch_aarch64.py", line 51, in ArchAArch64
    ks_arch = _keystone.KS_ARCH_ARM64
              ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'keystone' has no attribute 'KS_ARCH_ARM64'

**Comment by AndnixSH** [comment]
same issue

**Comment by seuxxd** [comment]
不要安装keystone，安装keystone-engine即可

don't install keystone,just keystone-engine
venv -> `pip3 uninstall keystone`
venv ->  `pip3 install keystone-engine`
